### ISSUE TITLE
Hey, i saw you added a PR to the original feroxrev's version of the Pokemon Go API. We took over the work and restarted the project here: https://github.com/Vulnova/Vulnova. Feel free to contribute. Thanks :)

### ISSUE THREAD

**Issue by Degix** [HelloKitty/PokemonGoDesktop.Unity#3]

**Comment by HelloKitty** [comment]
That's very unfortunate that he closed his work. Sort of disrespectful.

However, since I've generated my own protos based on POGOProtos with my own custom code generation, and built a light API to implement, I think I'll develop my own bot instead. Shame he closed the project.

I'd recommend you at the very least adopt the PokemonGoDesktop.API.Proto and Services. It contains far more protos defs with better field types and in the actual original format.
